version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  augur-processor:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: otel_scraper
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "4317:4317"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  augur-query-server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: query_server
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200