version: "3.8"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  augur:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: augur
    depends_on:
      - elasticsearch
    ports:
      - "4317:4317"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
