receivers:
  otlp:
    protocols:
      grpc:
      http:


  filelog:
    include:
      - /var/log/otel-logs/*.log  
    start_at: beginning

exporters:
  otlp:
    endpoint: "jaeger:4317"  
    tls:
      insecure: true

  otlphttp:
    endpoint: http://localhost:3100/otlp  #Loki endpoint

processors:
  batch:
    send_batch_size: 1024
    timeout: 10s
  attributes:
    actions:
      - action: insert
        key: service.name
        value: fake-service

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp] 

    logs:
      receivers: [filelog]
      processors: [batch, attributes]
      exporters: [otlphttp] 
