definitions:
  handler.ChainOfEventsNodeDTO:
    properties:
      cluster_id:
        description: The Cluster ID of the cluster belonging to the log or span data
        type: string
      log_dto:
        allOf:
        - $ref: '#/definitions/handler.LogDTO'
        description: The details of the log data, if the data is a log
      predecessors:
        description: The IDs of the predecessors of the log or span data
        items:
          $ref: '#/definitions/handler.EdgeDTO'
        type: array
      span_dto:
        allOf:
        - $ref: '#/definitions/handler.SpanDTO'
        description: The details of the span data, if the data is a span
      successors:
        description: The IDs of the successors of the log or span data
        items:
          $ref: '#/definitions/handler.EdgeDTO'
        type: array
    required:
    - cluster_id
    - predecessors
    - successors
    type: object
  handler.ChainOfEventsRequestDTO:
    properties:
      id:
        description: The ID of the log or span data
        type: string
    required:
    - id
    type: object
  handler.ChainOfEventsResponseDTO:
    properties:
      graph:
        additionalProperties:
          $ref: '#/definitions/handler.ChainOfEventsNodeDTO'
        description: The nodes in the chain of events
        type: object
    required:
    - graph
    type: object
  handler.DataResponseDTO:
    properties:
      data:
        description: The log or span representing the error
        items:
          $ref: '#/definitions/handler.LogAndSpanDTO'
        type: array
    type: object
  handler.EdgeDTO:
    properties:
      cluster_id:
        description: The Cluster ID of the associated log or span data
        type: string
      tdoa:
        description: The TDOA of the associated log or span data assuming a log or
          span was successfully inferred. Will be null if no successful inference
          was done.
        type: number
    required:
    - cluster_id
    type: object
  handler.ErrorMessage:
    properties:
      message:
        type: string
    type: object
  handler.LogAndSpanDTO:
    properties:
      log_dto:
        allOf:
        - $ref: '#/definitions/handler.LogDTO'
        description: The log details, null if the error is a span
      span_dto:
        allOf:
        - $ref: '#/definitions/handler.SpanDTO'
        description: The span details, null if the error is a log
    type: object
  handler.LogDTO:
    properties:
      cluster_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      message:
        type: string
      service:
        type: string
      severity:
        type: string
      span_id:
        type: string
      timestamp:
        type: string
      trace_id:
        type: string
    required:
    - cluster_id
    - created_at
    - id
    - message
    - service
    - severity
    - timestamp
    type: object
  handler.SpanDTO:
    properties:
      action_name:
        type: string
      attributes:
        additionalProperties:
          type: string
        type: object
      cluster_event:
        type: string
      cluster_id:
        type: string
      created_at:
        type: string
      end_time:
        type: string
      events:
        items:
          $ref: '#/definitions/handler.SpanEventDTO'
        type: array
      id:
        type: string
      parent_span_id:
        type: string
      service:
        type: string
      span_id:
        type: string
      span_kind:
        type: string
      start_time:
        type: string
      status:
        $ref: '#/definitions/handler.StatusDTO'
      trace_id:
        type: string
    required:
    - action_name
    - cluster_event
    - cluster_id
    - created_at
    - end_time
    - id
    - parent_span_id
    - service
    - span_id
    - span_kind
    - start_time
    - status
    - trace_id
    type: object
  handler.SpanEventDTO:
    properties:
      attributes:
        additionalProperties:
          type: string
        description: The attributes of the event, metadata like HTTP status, user
          info
        type: object
      name:
        description: The name of the event
        type: string
      timestamp:
        description: The timestamp of the event
        type: string
    required:
    - attributes
    - name
    - timestamp
    type: object
  handler.StatusCode:
    enum:
    - unset
    - ok
    - error
    type: string
    x-enum-varnames:
    - UNSET
    - OK
    - ERROR
  handler.StatusDTO:
    properties:
      code:
        $ref: '#/definitions/handler.StatusCode'
      message:
        type: string
    required:
    - code
    - message
    type: object
  log_and_span.SearchParams:
    properties:
      end_time:
        type: string
      operation:
        type: string
      service:
        type: string
      start_time:
        type: string
      type:
        items:
          $ref: '#/definitions/log_and_span.Type'
        type: array
    type: object
  log_and_span.Type:
    enum:
    - error
    - info
    - warn
    - ok
    - unset
    type: string
    x-enum-varnames:
    - Error
    - Info
    - Warn
    - Ok
    - Unset
info:
  contact: {}
  description: This is a monitoring and analytics tool for distributed systems.
  title: Augur API
  version: "1.0"
paths:
  /data:
    post:
      consumes:
      - application/json
      parameters:
      - description: The optional search parameters
        in: body
        name: searchParams
        required: true
        schema:
          $ref: '#/definitions/log_and_span.SearchParams'
      produces:
      - application/json
      responses:
        "200":
          description: List of logs and spans with their corresponding details.
          schema:
            $ref: '#/definitions/handler.DataResponseDTO'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorMessage'
      summary: Get spans or logs with their associated information.
      tags:
      - analytics
  /graph:
    post:
      consumes:
      - application/json
      parameters:
      - description: The log or span data to get the sub-graph from
        in: body
        name: logOrSpanData
        required: true
        schema:
          $ref: '#/definitions/handler.ChainOfEventsRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Sub-graph from the log or trace
          schema:
            $ref: '#/definitions/handler.ChainOfEventsResponseDTO'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorMessage'
      summary: Get a sub-graph from a log or trace.
      tags:
      - analytics
swagger: "2.0"
